version: "3.7"

services:
  prometheus:
    build:
      context: prometheus/
      dockerfile: prometheus_dockerfile
    image: prometheusimage
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    tty: true
    networks:
      - pg_network

  grafana:
    build:
      context: grafana/
      dockerfile: grafana_dockerfile
    image: grafanaimage
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    networks:
      - pg_network


networks:
  pg_network:
    driver: bridge

